# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install aws-cli and configure. Create a sample roles & policies
    init: |
      pip install awscli
      gp sync-done aws-cli
  - name: Create Neptune Cluster & Instance
    init: |
      gp sync-await aws-cli
      source ~/.bashrc
      echo "Set up aws-cli"
      read -p "Enter Your AWS Profile: " AWS_ID
      aws configure --profile $AWS_ID
      export AWS_PROFILE=$AWS_ID
      echo "List Roles and Policies"
      aws iam list-users --query 'Users[].UserName'
      aws iam list-groups-for-user --user-name $AWS_ID --query 'Groups[].GroupName'
      # aws iam list-policies --scope AWS
      aws iam list-policies --scope Local | jq ".Policies[].PolicyName"
      aws iam list-policies --only-attached | jq ".Policies[].PolicyName"
      aws iam list-roles | jq ".Roles[].RoleName"
      echo "Create Neptune Cluster & Instance"
      # ユーザー入力を変数に保持
      read -p "Enter Your Neptune cluster name: " NEP_CLUS
      # 変数と文字列の連結
      NEP_INST = "${NEP_CLUS}-cluster"
      # ARNは取り急ぎ既存の使い回し
      read -p "Enter Your Neptune Role ARN: " NEP_ARN
      aws neptune create-db-cluster --db-cluster-identifier $NEP_CLUS --engine neptune
      aws neptune create-db-instance --db-cluster-identifier $NEP_CLUS --engine neptune \
      --db-instance-identifier $NEP_INST --db-instance-class db.t3.medium
      aws neptune add-role-to-db-cluster --db-cluster-identifier $NEP_CLUS --role-arn $NEP_ARN
      aws neptune describe-db-clusters --db-cluster-identifier $NEP_CLUS
      aws neptune describe-db-instances --db-instance-identifier $NEP_INST
      # 実行結果を変数に保持
      # json返り値の特定のkeyのvalueを取り出す。"を外すための -r オプション
      DB_RES = `aws neptune describe-db-clusters --db-cluster-identifier $NEP_CLUS | jq -r ".DBClusters[].DbClusterResourceId"``
      

    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

