# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install aws-cli and configure. Create a sample roles & policies
    init: |
      pip install awscli
      read -p "Enter Your AWS Profile: " AWS_ID
      aws configure --profile $AWS_ID
      export AWS_PROFILE=$AWS_ID
    command: |
      pip install -t read_slack_data_to_put_S3_via_lambda slack_sdk --no-user
      echo -n "Will you create AWS policy and role for lambda？ [Y/n]: "
      read ANS
      case $ANS in
        "" | [Yy]* )
          sh configure_iam/example_lambda_role_with_S3Put.sh
          ;;
        * )
          echo "No"
          ;;
      esac
      echo -n "Will you create lambda function？ [Y/n]: "
      read ANS2
      case $ANS2 in
        "" | [Yy]* )
          sh read_slack_data_to_put_S3_via_lambda/test.sh
          ;;
        * )
          echo "No"
          ;;
      esac
      aws configure
      aws iam list-users --query 'Users[].UserName'
      aws iam list-groups-for-user --user-name $AWS_ID --query 'Groups[].GroupName'
      aws iam list-policies --scope AWS
      aws iam list-policies --scope Local
      aws iam list-policies --only-attached
      aws iam list-roles
      read -p "Enter Your SageMaker Notebook Name: " NOTE_ID
      aws sagemaker create-presigned-notebook-instance-url --notebook-instance-name $NOTE_ID

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
